### ISSUE TITLE
Change GameObjects type to std::array

### ISSUE THREAD

**Issue by jpvalle** [ucsd-cse-125-spring-2019/cse125-sp19-group5#31]
`gameObjects` was changed to be a "fixed" length array (maybe we should really change its type to `std::array` instead of `std::vector` to make it actually fixed length) which holds pointers to game objects.

In this case, 1024 is suppose to be the maximum number of game objects in the world, and `nullptr` is just to have the vector initially contain nulls. We can move the 1024 to a constant somewhere, though.

_Originally posted by @brianhang in https://github.com/ucsd-cse-125-spring-2019/cse125-sp19-group5/pull/30_

**Comment by brianhang** [comment]
One problem with using a vector is suppose you create two objects A and B. A will be given an ID like 123 and B will be given an ID like 124. Their indices within the `gameObjects` vector will match their ID. But, if object A gets deleted, then the vector will get shifted over and the IDs will no longer match the index. 

But, this means we have to be more careful about `nullptr` checks when iterating through `gameObjects`.

**Comment by jpvalle** [comment]
Won't the ID's be stored in the game objects as well though? I thought I heard @brianhang mention this
